# Blog info
blog_name: é–‹
slogan: å¾ç”Ÿä¹Ÿæœ‰æ¶¯, è€ŒçŸ¥ä¹Ÿæ— æ¶¯ã€‚
# Inclusive, Adaptive, Multifaceted, Innovative
# è®°å½•ä¸€ä¸ªå®‰å…¨æ¶æ„å¸ˆçš„æˆé•¿è¿‡ç¨‹
url: https://iami.xyz

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.png

# Set favicon
favicon: /favicon.ico

# For seo
keywords: å®‰å…¨æ¶æ„ å®‰å…¨æ¶æ„å¸ˆ ä¼ä¸šå®‰å…¨å»ºè®¾ æ•°æ®å®‰å…¨ åº”ç”¨å®‰å…¨ åŸºç¡€å®‰å…¨ SDLC å®‰å…¨ç ”å‘ æœºå™¨å­¦ä¹ ä¸äººå·¥æ™ºèƒ½ æœºå™¨å­¦ä¹ ä¸å…¥ä¾µæ£€æµ‹  

home_nav:

  - name: ä¹¦å•
    icon: icon-heart
    url: https://iread.cool
    target_blank: true #åœ¨æ–°é¡µé¢æ‰“å¼€
  # - name: CISOè¯´
  #   # icon: icon-feather
  #   url: https://ciso.chat
  #   target_blank: true #åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åšå®¢
    icon: icon-text
    url: /blog
    target_blank: false #ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  # - name: LinkedIn
  #   # icon: icon-user-1
  #   url: https://www.linkedin.com/in/zhaokunpeng
  #   target_blank: true
  # - name: RSS
  #   # icon: icon-rss
  #   url: https://iami.xyz/atom.xml
  #   target_blank: true
  

# config page nav
page_nav:
  # - name: åšå®¢
  #   url: /blog/
  #   target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: æœç´¢
    url: /search/
    target_blank: false # åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /category/
    target_blank: false
  - name: æ ‡ç­¾
    url: /tag/
    target_blank: false
  # - name: å…³äº
  #   url: /about/
  #   target_blank: false
  - name: ä¹¦å•
    url: https://iread.cool
    target_blank: true
  - name: è®¢é˜…
    url: /atom.xml
    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€

page_nav_style: ROUND_RECT  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: false # true|fase

# ç›’å­
toolbox:
  isShow: true # true|fase
  text: ğŸ¥· #â›ï¸
  # ğŸ”œ

search_slogan:
  isShow: true # true|fase
  text: ä¼ä¸šå®‰å…¨æ¶æ„ æ•°æ®å®‰å…¨ å®‰å…¨æ¶æ„ åº”ç”¨å®‰å…¨

# link_slogan:
#   isShow: true # true|fase
#   text: äº¤æ¢å‹é“¾å¯ä»¥é‚®ä»¶ forsigner@gmail.com

# set backtop show or hide
backtop:
  home: true
  archive: true
  category: true
  tag: true
  post: true
  link: true
  about: true

donation:
  show: false
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: å¦‚æœä½ è§‰å¾—æœ‰å¸®åŠ©
  items:
    # - type: å¾®ä¿¡
    #   text: å¾®ä¿¡æ‰«ä¸€æ‰«
    #   imgUrl: /images/qr-wechat.png
    # - type: æ”¯ä»˜å®
    #   text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
    #   imgUrl: /images/qr-alipay.jpg


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: false
  open_in_new_window: false
  show_prev_next: false

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: 

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—èƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
home_background_scheme: light # darkã€light

# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
# blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: Helvetica
blog_name_font_familiy: TESTFONT
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST #HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================
# Stats
google_analytics: G-6ELBN1SQMD
baidu_analytics: 

# Comment service
disqus_shortname: 
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# Valine comment system  https://valine.js.org
valine:
  enable: false # å¦‚æœä½¿ç”¨valineï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size



# ä¸ç®—å­,æ–‡ç« è®¿é—®é‡ç»Ÿè®¡å’Œæ˜¾ç¤º
busuanzi: true

# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================


link:
  - name:  
    info:  
    url: 
    avatar: 


project:
  - type: 
    name: 
    url:

#   - type: personal
#     name: machine learning for security
#     url: https://github.com/mylamour/machine-learning-for-security


#   - type: personal
#     name: flask ocr
#     url: https://github.com/mylamour/flask-ocr

    
#   - type: personal
#     name: python 2 pythonic
#     url: https://github.com/mylamour/python-and-pythonic
    

#   - type: personal
#     name: Forensic Tools
#     url: https://github.com/mylamour/-_--Forensics-Tools


#   - type: personal
#     name: Pastebin Spider
#     url: https://github.com/mylamour/pastebin-Spider